<?php
use Drupal\node\Entity\Node;
use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\webform\Entity\Webform;
use Drupal\webform\WebformSubmissionForm;
use Drupal\webform\Entity\WebformSubmission;

/**
 * @file
 * Contains mylist.module.
 */


/**
 * Implements hook_theme().
 */
function mylist_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
// dd($form_state);
if($form_id == 'node_test_edit_form'){
 

  $node = $form_state->getFormObject()->getEntity();
  // dd($node);
  $mail=$node->get('field_mail')->value;
  $body=$node->get('body')->value;
$status=$node->get('status')->value;
if($status == 1) {
    $webform_id = 'test';	// here use can use that webform id where to save data
      $webform = Webform::load($webform_id);
      // Create webform submission.
      $values = [
      'webform_id' => $webform->id(),
      'data' => [
      'body' => $body,
      'mail' => $mail,
      ],
      ];
  /** @var \Drupal\webform\WebformSubmissionInterface $webform_submission */
      $webform_submission = WebformSubmission::create($values);
      $webform_submission->save(); 
  // dpm($webform_submission);
}
}
}